name: Stale Issue & PR Handler

on:
  schedule:
    - cron: "35 5 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read
  issues: write
  pull-requests: write

jobs:
  stale:
    name: Run Stale Issue & PR Handler
    uses: ./.github/workflows/reusable-stale.yml

  status-check:
    name: Check Jobs Status
    needs:
      - stale
    if: always()
    # ðŸ”´ IMPORTANT: this is a *job-level* uses, not under steps:
    uses: ./.github/workflows/reusable-check-jobs-status.yml

  slack-workflow-status:
    name: Slack Post Workflow Notification
    needs:
      - stale
    if: always()

    uses: ./.github/workflows/reusable-slack-workflow-status.yml
    with:
      notify_on_results: "failed,timed_out"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
