name: Purge Deprecated Workflow Runs

on:
  workflow_dispatch:

  schedule:
    - cron: '33 3 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  purge-deprecated-workflows:
    name: Run Purge Deprecated Workflow Runs (Reusable)
    uses: ./.github/workflows/reusable-purge-deprecated-workflow-runs.yml

  status-check:
    name: Check Jobs Status
    needs:
      - purge-deprecated-workflows
    if: always()
    # ðŸ”´ IMPORTANT: this is a *job-level* uses, not under steps:
    uses: ./.github/workflows/reusable-check-jobs-status.yml
    with:
      ignore_jobs: "Check Job Status"

  slack-workflow-status:
    name: Slack Workflow Status
    needs:
      - purge-deprecated-workflows
    if: always()

    uses: ./.github/workflows/reusable-slack-workflow-status.yml
    with:
      notify_on_results: "failed,timed_out"
      ignore_jobs: "Check Jobs Status"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
