name: Reusable pydocstyle (Docstring Style Checker)

on:
  workflow_call:
    inputs:
      include_files:
        description: "Comma-separated list of files (or regex) to include"
        required: false
        type: string
      exclude_files:
        description: "Comma-separated list of files (or regex) to exclude"
        required: false
        type: string
      report_only:
        description: "Generate a report but do not fail the build"
        required: false
        type: boolean
        default: false
      show_errors:
        description: "Show detailed errors"
        required: false
        type: boolean
        default: true
      show_skipped:
        description: "Show skipped files"
        required: false
        type: boolean
        default: false
      no_color:
        description: "Disable coloured output"
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  pydocstyle:
    name: Pydocstyle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Run Pydocstyle
        env:
          INCLUDE_FILES: ${{ inputs.include_files }}
          EXCLUDE_FILES: ${{ inputs.exclude_files }}
          REPORT_ONLY: ${{ inputs.report_only }}
          SHOW_ERRORS: ${{ inputs.show_errors }}
          SHOW_SKIPPED: ${{ inputs.show_skipped }}
          NO_COLOR: ${{ inputs.no_color }}
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/pydocstyle/master/pipeline.sh)
