name: Reusable awesomebot (Links & Anchors Validator)

on:
  workflow_call:
    inputs:
      flags:
        description: "Command-line flags to pass to awesomebot"
        required: false
        type: string
        default: "default"
      whitelist:
        description: "Comma-separated list of files (or regex) to whitelist"
        required: false
        type: string
      include_files:
        description: "Comma-separated list of files (or regex) to include"
        required: false
        type: string
      exclude_files:
        description: "Comma-separated list of files (or regex) to exclude"
        required: false
        type: string
      report_only:
        description: "Generate a report but do not fail the build"
        required: false
        type: boolean
        default: false
      show_errors:
        description: "Show detailed errors"
        required: false
        type: boolean
        default: true
      show_skipped:
        description: "Show skipped files"
        required: false
        type: boolean
        default: false
      no_color:
        description: "Disable coloured output"
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  awesomebot:
    name: Awesomebot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      - name: Setup Ruby 3.4
        uses: ruby/setup-ruby@d697be2f83c6234b20877c3b5eac7a7f342f0d0c  # v1.269.0
        with:
          ruby-version: "3.4"

      - name: Run Awesomebot
        env:
          FLAGS: ${{ inputs.flags }}
          WHITELIST: ${{ inputs.whitelist }}
          INCLUDE_FILES: ${{ inputs.include_files }}
          EXCLUDE_FILES: ${{ inputs.exclude_files }}
          REPORT_ONLY: ${{ inputs.report_only }}
          SHOW_ERRORS: ${{ inputs.show_errors }}
          SHOW_SKIPPED: ${{ inputs.show_skipped }}
          NO_COLOR: ${{ inputs.no_color }}
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/awesomebot/master/pipeline.sh)
