name: Reusable PHP Lint (Syntax Checker)

on:
  workflow_call:
    inputs:
      include_files:
        description: "Comma-separated list of PHP files / globs to include (regex supported)"
        required: false
        type: string
      exclude_files:
        description: "Comma-separated list of PHP files / globs to exclude (regex supported)"
        required: false
        type: string
      report_only:
        description: "Generate report but do not fail build"
        required: false
        type: boolean
        default: false
      show_errors:
        description: "Show individual errors instead of only per-file summary"
        required: false
        type: boolean
        default: true
      show_skipped:
        description: "Show files that are skipped"
        required: false
        type: boolean
        default: false
      no_color:
        description: "Disable coloured output"
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  php-lint:
    name: PHP Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Run PHP Lint
        env:
          INCLUDE_FILES: ${{ inputs.include_files }}
          EXCLUDE_FILES: ${{ inputs.exclude_files }}
          REPORT_ONLY: ${{ inputs.report_only }}
          SHOW_ERRORS: ${{ inputs.show_errors }}
          SHOW_SKIPPED: ${{ inputs.show_skipped }}
          NO_COLOR: ${{ inputs.no_color }}
        run: |
          bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/php-lint/master/pipeline.sh)
